Display log in case of testsuite faillure
It will help with hurd test faillure

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -121,13 +121,19 @@ override_dh_auto_build-indep:
 	cd debian/build-quantum-indep/PerlMagick/default/ && make
 
 # dh_auto_test in build directory
+# display log in case of failure
 quantum_override_dh_auto_test-arch_%:
 	if test "BUG#703262" = "SOLVED" ; then \
-	unset DISPLAY; dh_auto_test --builddirectory="debian/build-quantum-$*"; \
+        unset DISPLAY; \
+	if ! dh_auto_test --builddirectory="debian/build-quantum-$*"; then \
+		(cd "debian/build-quantum-$*/tests" && find -name *.log -exec cat {} \;); \
+	fi; \
 	else \
 	if test "$(DEB_HOST_GNU_TYPE)" = "$(DEB_BUILD_GNU_TYPE)"; then \
             unset DISPLAY; \
-	    dh_auto_test --builddirectory="debian/build-quantum-$*"; \
+	    if ! dh_auto_test --builddirectory="debian/build-quantum-$*"; then \
+		(cd "debian/build-quantum-$*/tests" && find -name *.log -exec cat {} \;); \
+	    fi; \
 	fi ;\
 	fi
 override_dh_auto_test-arch: quantum_override_dh_auto_test-arch_Q16
